### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ElchananHaas** [patricksongzy/computational-graph#7]
Excellent repository! I am trying to use this repository for some reinforcement learning. Is there any way to use this as a dependency in a larger Maven project?

**Comment by patricksongzy** [comment]
Hello Elchanan,

I haven't uploaded this as an artefact to any repositories, so at the moment to get this working, you would have to clone the project, run `mvn install`, and add it to your `pom.xml` file. I might look into doing so in the future.

Depending on what task you are trying to accomplish with reinforcement learning, you may need to add some additional operators to the library. At the current time, only GEMM (matrix multiplication), element-wise addition, and element-wise multiplication are implemented, with tensor broadcasting [here](https://github.com/patricksongzy/computational-graph/blob/master/src/main/java/graph/node/operation/). Implementing most operators, especially if already supported by CLBlast should be pretty straightforward. If there are specific operators you would like me to implement, I could look into doing so.

For a (naturally) more developed, and supported ecosystem in Java, you might want to check out [DL4J](https://deeplearning4j.org/), or [ND4J](https://github.com/eclipse/deeplearning4j/tree/master/nd4j), which is a part of DL4J.
